
//This file should be called cbmc_main_loan.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_loan.c F_loan.c


#include "F_loan.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for loan
	enforcervars_loan_t enf_loan;
    inputs_loan_t inputs_loan;
    outputs_loan_t outputs_loan;

	//set values to known state
    loan_init_all_vars(&enf_loan, &inputs_loan, &outputs_loan);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_loan.A = nondet_loan_input_0();
	inputs_loan.B = nondet_loan_input_1();
	inputs_loan.C = nondet_loan_input_2();
	inputs_loan.D = nondet_loan_input_3();
	inputs_loan.E = nondet_loan_input_4();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	enf_loan.b = nondet_loan_enf_p1_0();
	
	enf_loan._policy_p1_state = nondet_loan_enf_p1_state() % 2;
	
	enf_loan._policy_p2_state = nondet_loan_enf_p2_state() % 2;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	loan_run_via_enforcer(&enf_loan, &inputs_loan, &outputs_loan);

}


void loan_run(inputs_loan_t *inputs, outputs_loan_t *outputs) {
    //randomise controller

    outputs->P1 = nondet_loan_output_0();
	outputs->P2 = nondet_loan_output_1();
	 
}

