
//This file should be called F_loan.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_loan.h"

void loan_init_all_vars(enforcervars_loan_t* me, inputs_loan_t* inputs, outputs_loan_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_p1_state = POLICY_STATE_loan_p1_s0;
	//input policy internal vars
	
	me->b = 0;
	
	
	me->_policy_p2_state = POLICY_STATE_loan_p2_s0;
	//input policy internal vars
	
	
}

void loan_run_via_enforcer(enforcervars_loan_t* me, inputs_loan_t* inputs, outputs_loan_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 loan_run_input_enforcer_p2(me, inputs);
	 loan_run_input_enforcer_p1(me, inputs);
	

	loan_run(inputs, outputs);

	//run policies in specified order for outputs
	loan_run_output_enforcer_p1(me, inputs,outputs);
	loan_run_output_enforcer_p2(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY p1 BEGIN
//This will run the input enforcer for loan's policy p1
void loan_run_input_enforcer_p1(enforcervars_loan_t* me, inputs_loan_t* inputs) {
	switch(me->_policy_p1_state) {
		case POLICY_STATE_loan_p1_s0:
			
			
			break;

		case POLICY_STATE_loan_p1_s1:
			
			if(inputs->E && me->b < 2) {
				//transition s1 -> violation on E and b < 2
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 
			
			break;

		
	}
}

//INPUT POLICY p1 END

//INPUT POLICY p2 BEGIN
//This will run the input enforcer for loan's policy p2
void loan_run_input_enforcer_p2(enforcervars_loan_t* me, inputs_loan_t* inputs) {
	switch(me->_policy_p2_state) {
		case POLICY_STATE_loan_p2_s0:
			
			
			break;

		case POLICY_STATE_loan_p2_s1:
			
			if(inputs->A) {
				//transition s1 -> violation on A
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 
			
			break;

		
	}
}

//INPUT POLICY p2 END



//output policies

//OUTPUT POLICY p1 BEGIN
//This will run the input enforcer for loan's policy p1
void loan_run_output_enforcer_p1(enforcervars_loan_t* me, inputs_loan_t* inputs, outputs_loan_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_p1_state) {
		case POLICY_STATE_loan_p1_s0:
			

			break;

		case POLICY_STATE_loan_p1_s1:
			
			if(inputs->E && me->b < 2) {
				//transition s1 -> violation on ( E and b < 2 )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->P1 = 1;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_p1_state) {
		case POLICY_STATE_loan_p1_s0:
			
			if(inputs->B) {
				//transition s0 -> s1 on B
				me->_policy_p1_state = POLICY_STATE_loan_p1_s1;
				//set expressions
				
				me->b = 1;
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "loan_p1_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_loan_p1_s1:
			
			if(inputs->B) {
				//transition s1 -> s1 on B
				me->_policy_p1_state = POLICY_STATE_loan_p1_s1;
				//set expressions
				
				me->b = 2;
				break;
			} 
			if(inputs->E && me->b == 2) {
				//transition s1 -> s1 on ( E and b = 2 )
				me->_policy_p1_state = POLICY_STATE_loan_p1_s1;
				//set expressions
				
				break;
			} 
			if(inputs->E && me->b < 2) {
				//transition s1 -> violation on ( E and b < 2 )
				me->_policy_p1_state = POLICY_STATE_loan_p1_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "loan_p1_s1 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_p1_state != POLICY_STATE_loan_p1_violation);
}

//OUTPUT POLICY p1 END

//OUTPUT POLICY p2 BEGIN
//This will run the input enforcer for loan's policy p2
void loan_run_output_enforcer_p2(enforcervars_loan_t* me, inputs_loan_t* inputs, outputs_loan_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_p2_state) {
		case POLICY_STATE_loan_p2_s0:
			

			break;

		case POLICY_STATE_loan_p2_s1:
			
			if(inputs->A) {
				//transition s1 -> violation on A
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->P2 = 1;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_p2_state) {
		case POLICY_STATE_loan_p2_s0:
			
			if(inputs->A) {
				//transition s0 -> s1 on A
				me->_policy_p2_state = POLICY_STATE_loan_p2_s1;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "loan_p2_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_loan_p2_s1:
			
			if(inputs->A) {
				//transition s1 -> violation on A
				me->_policy_p2_state = POLICY_STATE_loan_p2_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "loan_p2_s1 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_p2_state != POLICY_STATE_loan_p2_violation);
}

//OUTPUT POLICY p2 END



//This function is provided in "F_loan.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

